theme: jekyll-theme-architect

domain: avipars.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://avipars.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /     # place folder name if the site is served in a subfolder

title: CS Resources 
description: Computer Science Resources and Links from Avi Parshan

remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# Includes an icon in the footer for each user name you enter
footer-links:
  github: avipars
  twitter: aviinfinity

show_downloads: false