theme: jekyll-theme-architect

domain: avipars.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://avipars.github.io/CS-Resources  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /CS-Resources/      # place folder name if the site is served in a subfolder

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
