theme: jekyll-theme-architect

domain: cs.aviparshan.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cs.aviparshan.com  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /     # place folder name if the site is served in a subfolder

title: "CS Resources"
description: "Computer Science Resources and Links from Avi Parshan"
subtitle: "Useful Computer Science Resources and Links"  # site tagline that appears below site title in masthead
locale: "en-US"

remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-redirect-from # handle external posts

  # - jekyll-sitemap


# config settings for relative links 
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - _pages
# exclude :
#  - 404.md
#  - 404.html 

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
# Includes an icon in the footer for each user name you enter
footer-links:
  github: avipars
  twitter: aviinfinity

future: true #render future posts

show_downloads: false # hide github ugly download button

# Site Author
author:
  name             : "Avi Parshan"
  avatar           : "https://github.com/avipars/aviparshan_site/blob/master/img/avi_parshan_profile_avatar.png?raw=true"
  bio              : "I am an **amazing** person."
  location         : "Israel"
  email            : "cs@aviparshan.com"

# default settings for files (latter half is for excluding from sitemap)
defaults:

  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: page

  - scope:
      path: "/*.xml"
    values:
      sitemap: false   

  - scope:
      path: "/**/*.css"
    values:
      sitemap: false

  - scope:
      path: "/**/*.json"
    values:
      sitemap: false