name: Jekyll Deploy

on:
  push:
    branches:
      # deploy on updates on main
      - main
  schedule:
    # redeploy every morning to update unpublished pages
    - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: create gem
        run: echo "bundle gem lorem"
      - name: gem2
        run: echo "jekyll new --skip-bundle ."
      - name: gem3
        run: echo "gem "github-pages", "~> 3.9.2", group::jekyll_plugins"
        
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/gems
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build & Deploy to GitHub Pages
        uses: DavidS/jekyll-deploy@main
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
